# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: research/
    weight: 20
  - name: Publications
    url: publications/
    weight: 30
  - name: Team
    url: team/
    weight: 40
  - name: Software
    url: software/
    weight: 50
  - name: Teaching
    url: teaching/
    weight: 60

