blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://discord.gg/z8wNYzb
    about: Chat live with the Hugo Blox Builder community on Discord.
  - name: Discussions
    url: https://github.com/HugoBlox/hugo-blox-builder/discussions
    about: Discuss Hugo Blox Builder on the GitHub Discussions forum
  - name: Troubleshooting Guide
    url: https://docs.hugoblox.com/reference/troubleshooting/
    about: Solve common issues fast.
  - name: Documentation
    url: https://docs.hugoblox.com/
    about: Review the documentation
